FROM openjdk:11 AS build

RUN mkdir /build
COPY / /build

WORKDIR /build
RUN ./mvnw clean package -Pprod

FROM openjdk:11

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JHIPSTER_SLEEP=0 \
    JAVA_OPTS=""

# Add a jhipster user to run our application so that it doesn't need to run as root
RUN adduser --shell /bin/sh jhipster
WORKDIR /home/jhipster

COPY src/main/docker/entrypoint.sh entrypoint.sh
RUN chmod 755 entrypoint.sh && chown jhipster:jhipster entrypoint.sh
USER jhipster

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 8080

COPY --from=build /build/target/*.war app.war
