export const enum LocationFields {
  NAME = 'NAME',
  ALTERNATE_NAME = 'ALTERNATE_NAME',
  DESCRIPTION = 'DESCRIPTION',
  TRANSPORTATION = 'TRANSPORTATION',
  LATITUDE = 'LATITUDE',
  LONGITUDE = 'LONGITUDE',
  REGULAR_SCHEDULE_NOTES = 'REGULAR_SCHEDULE_NOTES',
  PHYSICAL_ADDRESS = 'PHYSICAL_ADDRESS',
  POSTAL_ADDRESS = 'POSTAL_ADDRESS',
  REGULAR_SCHEDULE_OPENING_HOURS = 'REGULAR_SCHEDULE_OPENING_HOURS',
  LANGS = 'LANGS',
  HOLIDAY_SCHEDULES = 'HOLIDAY_SCHEDULES'
}

export interface ILocationFieldsValue {
  id?: number;
  locationField?: LocationFields;
}

export const defaultValue: Readonly<ILocationFieldsValue> = {};
