package org.benetech.servicenet.domain.enumeration;

/**
 * The ServiceFields enumeration.
 */
public enum ServiceFields {
    NAME, ALTERNATE_NAME, DESCRIPTION, URL, EMAIL, STATUS, INTERPRETATION_SERVICES, APPLICATION_PROCESS, WAIT_TIME, FEES,
    ACCREDITATIONS, LICENSES, TYPE, ELIGIBILITY, FUNDING, DOCS, PAYMENTS_ACCEPTEDS, TAXONOMIES,
    REGULAR_SCHEDULE_OPENING_HOURS, LANGS, HOLIDAY_SCHEDULES, CONTACTS, PHONES
}
